### ISSUE TITLE
Series already in my collection

### ISSUE THREAD

**Issue by Deterio** [poketo/poketo-reader#50] opened 2019-03-17 18:52 UTC
When adding series to my collection, it says the series is already added to my collection.
![](https://i.imgur.com/3lsGfgY.png)

But when I refresh the page, nothing shows up.
![](https://i.imgur.com/dVNw8UL.png)

**Comment by rosszurowski** [comment] 2019-03-18 12:51
Hey! Sorry for all the troubles you're running into.

Looks like this was a bug caused by a recent change to the duplicate bookmark logic. I had it backwards, so new bookmarks would accidentally be marked as duplicates and duplicates would be fine.

I pushed a fix for this (5c79f3e48a65c72ea854dbc5503cf1698bd2c7bc), and it shouldn't be an issue anymore.

**Closed by rosszurowski** 2019-03-18 12:51 UTC

**Comment by Deterio** [comment] 2019-03-18 17:41
Totally fine, I don't mind helping out by reporting a bit 😄
